CREATE TABLE BOARD (
	BOARD_ID	NUMBER PRIMARY KEY,
	TITLE		VARCHAR2(256) NOT NULL,
	WRITER		VARCHAR2(50) NOT NULL,
	PASSWORD	VARCHAR2(20) NOT NULL,
	READ_CNT	NUMBER DEFAULT(0),
	CONTENT		CLOB,
	REG_DATE	DATE DEFAULT(SYSDATE),
	UPDATE_DATE	DATE DEFAULT(SYSDATE)
);

CREATE SEQUENCE BOARD_SEQ;